### ISSUE TITLE
Support Vale suggestions

### ISSUE THREAD

**Issue by eread** [admhlt/SublimeLinter-contrib-vale#10]
The SublimeLinter-vale package supports two of the three [available alert levels](https://vale.sh/docs/topics/config/#minalertlevel):

- `error`
- `warning`

It would be great if it could also support `suggestion`.

**Comment by kaste** [comment]
This is probably a simple change on our regex.  You could try a PR or post some example output from vale we need to support and parse.

**Comment by eread** [comment]
> This is probably a simple change on our regex. You could try a PR or post some example output from vale we need to support and parse.

@kaste I think that's right!

Looking at:

https://github.com/SublimeLinter/SublimeLinter-vale/blob/0cd7c5a1841af358ae6d0ce4df934fffb4b0d74b/linter.py#L25

the package is picking up `error` and `warning` from the output of the `vale` command:

https://github.com/SublimeLinter/SublimeLinter-vale/blob/0cd7c5a1841af358ae6d0ce4df934fffb4b0d74b/linter.py#L22


It looks like it's simply ignoring `suggestion`. There's sample output on the Vale website main page: https://vale.sh.

The second column contains either `error`, `warning`, or `suggestion`.

I think the required diff is:

```diff
-        r'((?P<error>error)|(?P<warning>warning))\s{2,}'
+        r'((?P<error>error)|(?P<warning>warning)|(?P<suggestion>suggestion))\s{2,}'
```

**Comment by kaste** [comment]
Yeah almost.  I think we need to use the capturing group `error_type`.  Maybe like so

```
-        r'((?P<error>error)|(?P<warning>warning))\s{2,}'
+        r'(?P<error_type>\S+)\s{2,}'
```
